### ISSUE TITLE
Missing xcrun command

### ISSUE THREAD

**Issue by frakman1** [Qusic/theos#1]
I am trying to compile the tweaks located in the link below: 

https://github.com/CPDigitalDarkroom/Infiniapps/blob/master/infinidock/Makefile

As you can see, the Makefile calls for the command `xcrun` as in:
`export TARGET_CXX = xcrun -sdk iphoneos clang++`

However, I get this error when I try to compile:
`bash: xcrun: command not found`

**Comment by Qusic** [comment]
you can try to remove that line. theos can find the proper clang++ on its own.
this seems a very old tweak and you are likely to encounter many build issues even on a real mac (with current version of theos and sdks).

**Comment by frakman1** [comment]
Thank you. I got past that error but unfortunately ran into another one as you predicted.
Including here only as an FYI:

```
Infinidock.xmi:485: error: %init for an undefined %group IFBasic
```

Since this is not an issue with the build environment but with the tweak, this issue can be closed.
